### ISSUE TITLE
Error: could not read Password

### ISSUE THREAD

**Issue by CWSites** [sterlingwes/gh-pages-deploy-action#3]
I'm running into this error and not sure what's going on. Are there particular permissions that need to be used for this to work?

```bash
git push -f https://***@github.com/digital-ai/dot-components.git HEAD:ghpages
fatal: could not read Password for 'https://***@github.com': No such device or address
Error: The process 'git' failed with exit code 128
```

**Comment by CWSites** [comment]
Looks like you need to have a `PAT` with write access on the repo for this to work. You may want to update the readme to notate this :)

**Comment by sterlingwes** [comment]
It's already noted:

![Screen Shot 2021-08-28 at 12 36 03 PM](https://user-images.githubusercontent.com/1047502/131224713-97a3a00f-bfed-42ee-8d3b-d48447267d30.png)

Glad you figured it out tho!
